//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар На Складе.
    /// </summary>
    // *** Start programmer edit section *** (StoreProduct CustomAttributes)

    // *** End programmer edit section *** (StoreProduct CustomAttributes)
    [AutoAltered()]
    [Caption("Товар На Складе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StoreProductE", new string[] {
            "Product as \'Товар\'",
            "Product.Name as \'\'",
            "Amount as \'Количество\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("StoreProductE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class StoreProduct : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.Shop.Product fProduct;
        
        private IIS.Shop.StoreHouse fStoreHouse;
        
        // *** Start programmer edit section *** (StoreProduct CustomMembers)

        // *** End programmer edit section *** (StoreProduct CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Amount CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Amount Get start)

                // *** End programmer edit section *** (StoreProduct.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (StoreProduct.Amount Get end)

                // *** End programmer edit section *** (StoreProduct.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Amount Set start)

                // *** End programmer edit section *** (StoreProduct.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (StoreProduct.Amount Set end)

                // *** End programmer edit section *** (StoreProduct.Amount Set end)
            }
        }
        
        /// <summary>
        /// Товар На Складе.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Product CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Product"})]
        public virtual IIS.Shop.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Product Get start)

                // *** End programmer edit section *** (StoreProduct.Product Get start)
                IIS.Shop.Product result = this.fProduct;
                // *** Start programmer edit section *** (StoreProduct.Product Get end)

                // *** End programmer edit section *** (StoreProduct.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Product Set start)

                // *** End programmer edit section *** (StoreProduct.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (StoreProduct.Product Set end)

                // *** End programmer edit section *** (StoreProduct.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shop.StoreHouse.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.StoreHouse CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.StoreHouse CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "StoreHouse"})]
        public virtual IIS.Shop.StoreHouse StoreHouse
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.StoreHouse Get start)

                // *** End programmer edit section *** (StoreProduct.StoreHouse Get start)
                IIS.Shop.StoreHouse result = this.fStoreHouse;
                // *** Start programmer edit section *** (StoreProduct.StoreHouse Get end)

                // *** End programmer edit section *** (StoreProduct.StoreHouse Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.StoreHouse Set start)

                // *** End programmer edit section *** (StoreProduct.StoreHouse Set start)
                this.fStoreHouse = value;
                // *** Start programmer edit section *** (StoreProduct.StoreHouse Set end)

                // *** End programmer edit section *** (StoreProduct.StoreHouse Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StoreProductE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StoreProductE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StoreProductE", typeof(IIS.Shop.StoreProduct));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of StoreProduct.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfStoreProduct CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfStoreProduct CustomAttributes)
    public class DetailArrayOfStoreProduct : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shop.DetailArrayOfStoreProduct members)

        // *** End programmer edit section *** (IIS.Shop.DetailArrayOfStoreProduct members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type StoreProduct by index.
        /// </summary>
        /// <summary>
        /// Adds object with type StoreProduct.
        /// </summary>
        public DetailArrayOfStoreProduct(IIS.Shop.StoreHouse fStoreHouse) : 
                base(typeof(StoreProduct), ((ICSSoft.STORMNET.DataObject)(fStoreHouse)))
        {
        }
        
        public IIS.Shop.StoreProduct this[int index]
        {
            get
            {
                return ((IIS.Shop.StoreProduct)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shop.StoreProduct dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
